### ISSUE TITLE
Typo in readme 

### ISSUE THREAD

**Issue by aboraks** [mhelmetag/gosurf#1]
Sorry if this is not the correct spot or appropriate method. I'm very new to Git

Typo in readme 

"To search for regions in Central America, specify regions as the place type (--pt regions) and then provide the area ID (--a 4710)" 

(--pt regions) 
should read 
(--t regions)

**Comment by mhelmetag** [comment]
Yeah, this is totally the right place! Good eyes!

Would you want to make the PR to fix it?

**Comment by aboraks** [comment]
What a pleasant learning experience,

Thanks

**Comment by mhelmetag** [comment]
Course! Good luck. Lemme know if you want any help.

**Comment by mhelmetag** [comment]
I took a sneak peak at your branch... looks great! Whenever you get around to making a PR, I'll merge that in 😄

**Comment by aboraks** [comment]
Hmmm, ok. Thanks for the follow-up.

I guess I'm not really sure what I'm doing. I'll take a look at it in the
morning.

Andre

**Comment by mhelmetag** [comment]
This might help: https://help.github.com/en/articles/creating-a-pull-request

Also I could jump on a google hangout for a few minutes sometime too.

**Comment by aboraks** [comment]
That was a big help,

Thanks

**Comment by mhelmetag** [comment]
Resolved in #2

**Comment by mhelmetag** [comment]
Course! Glad that helped! Thanks again for the edit!
